name: drinkwell_balance_checker
description: A Flutter app to check Drinkwell water ATM card balance by reference number, mobile number or card number.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI related packages
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

  # State management
  provider: ^6.0.5

  # For API requests
  http: ^0.13.6

  # For local storage
  shared_preferences: ^2.2.2

  # For animations
  flutter_animate: ^4.2.0
