name: flutter Android Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout source
        uses: actions/checkout@v3

      # 2. Setup Java (Android build এর জন্য দরকার)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # আপনার Flutter version অনুযায়ী পরিবর্তন করুন
          
      # 4. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 5. Run tests (optional, পুলিশে কাম নিয়েও পারবেন)
      - name: Run tests
        run: flutter test

      # 6. Build APK
      - name: Build APK
        run: flutter build apk --release

      # 7. Upload APK artifact (আর্টিফ্যাক্ট সেভ করার জন্য)
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4 # ভার্সন v4-এ আপডেট করা হলো
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
